create database chat_app;

create table users(
  user_id int generated by default as identity primary key,
  role smallint default 0,
  username varchar(40) not null,
  password varchar(70) not null,
  full_name text not null
);

create table messages(
  message_id int generated by default as identity primary key,
  text text not null,
  time timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  user_id int references users(user_id) on delete set null
);

create unique index username_idx on users (lower(username));

create extension pgcrypto;